### PR TITLE
Added postcss.config.js

### PR DESCRIPTION
**Pull request by viktor992**
I was getting the following error on startup:

```
=> Errors prevented startup:                  
   
   While processing files with akryum:vue-component (for target web.browser):
   client/components/app-layout.vue:162: [vue-component] Error while configuring PostCSS (custom configuration) in tag <style> PostCSS config Error: Loading
   PostCSS Plugin failed: Cannot find module 'postcss-easy-import'

```

Added required configuration file.

### CODE REVIEW

**Comment by mitar** [comment]
I think this is not the right fix. With this you disable postcss completely? And this is why it then does not try to load the plugin. [We have configuration in `package.json`](https://github.com/peer/doc/blob/master/package.json#L66).

But yea, I do not know why this is working for me and it does not work on clean installation.

**Comment by mitar** [comment]
I think this is the same issue: https://github.com/meteor-vue/vue-meteor/issues/312

**Comment by mitar** [comment]
Does this really fix things for you?

**Comment by mitar** [comment]
Closing in favor of 6cc67474585b4b50b8ddd738535e8821371d3a77.

**Comment by mitar** [comment]
I couldn't get this to work with your fix. How did you came up with this fix? It is very close to the working one.

**Comment by viktor992** [comment]
I've found a similar issue with postcss configuration and tried this: https://github.com/akveo/ngx-admin/issues/604#issuecomment-271974780. Apparently it worked for me. But I agree with closing in favor of your fix.

**Pull request closed without merging**
