### PR TITLE
Change editor toolbar appearance

### PR DESCRIPTION
**Pull request by voluntadpear**
This PR addresses #17. The overall appearance of the editor toolbar was changed.

image

The `flat` style of `v-button` was adopted and vertical divider lines were added. 

**Note**: This PR should be merged after #11

### CODE REVIEW

**Comment by mitar** [comment]
There are conflicts.

One small thing. Could you use `strikethrough s` icon instead of `format strikethrough`? It will be then more similar to Google Doc. :-)

**Comment by mitar** [comment]
One other style suggestion: can you make it so that there is no space between buttons. And then there is space only between groups. And then there is no need for vertical divider? See [style here](https://vuetifyjs.com/components/buttons#example-4).

**Comment by voluntadpear** [comment]
image I removed the vertical divider and added extra space between groups. Also, changed the `strikethrough` icon as requested

**Comment by mitar** [comment]
Great!

Can you make it also to have a shadow around, see [here](https://vuetifyjs.com/components/buttons#example-4). I think this is what `toolbar` component provides?

**Comment by mitar** [comment]
If this is ready to be reviewed and merged (after parent PR is merged), please remove `WiP`.

**Comment by voluntadpear** [comment]
I added the shadow and I think this is ready to be reviewed and merge after #1 is merged.

**Pull request merged**
