### PR TITLE
Make editor toolbar sticky as you scroll

### LINKED ISSUE #10: Make editor toolbar sticky as you scroll
* When the user scrolls down and it moves with top window border pass the toolbar, toolbar should detach and start following scrolling and be on the top of the window.

### PR DESCRIPTION
**Pull request by voluntadpear**
Fixes #10 

I added a scroll watcher to the editor toolbar to check whether the toolbar is currently visible in the window or not, and if it's going to be hidden then add the `fixed` property to the `v-toolbar` component to make it sticky at the top of the window.

Before scrolling:

image

After scrolling:
image

**Note**: There is a remaining linter error that will be fixed by a commit that Dani will push later, and then it should be ready to merge.

### CODE REVIEW

**Comment by mitar** [comment]
This is on top of #11? Does it supered it or should we first finalize/merge #11?

**Comment by mitar** [comment]
From screenshots it seems like the toolbar changes in shape (becomes wider). Can you make sure it smoothly moves and stays of the same shape.

**Comment by voluntadpear** [comment]
We should first merge #11 😀

**Comment by voluntadpear** [comment]
Sure! I'll work on that

**Comment by mitar** [comment]
Also, make sure if there is left-right scrollbar on the window for some reason, that toolbar stays aligned with the editor.

**Comment by mitar** [comment]
(Not sure if this is a problem here, but I have seen it elsewhere.)

**Comment by mitar** [comment]
If this is ready to be reviewed and merged (after parent PR is merged), please remove `WiP`.

**Comment by voluntadpear** [comment]
Adding the `WiP` tag again because I'm working on a little fix when resizing the window after the toolbar has been fixed

**Pull request merged**
